os: osx
osx_image: xcode9.2 
language: swift

before_install: 
  - bash decryptCertificates.sh

before_script:
  - bash add-keys.sh
  - bash update-bundle.sh


script:
  - pod install  
 

  #- xcodebuild clean build test -workspace DemoCI.xcworkspace -scheme "DemoCI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO #DEVELOPMENT_TEAM=E46WB37LUW
  #- xcodebuild -workspace DemoCI.xcworkspace -scheme "DemoCI" -sdk iphoneos -configuration Release -allowProvisioningUpdates -derivedDataPath build/ -archivePath ArchiveFolder/DemoCI.xcarchive ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO archive
  - xcodebuild -workspace DemoCI.xcworkspace -scheme "DemoCI" -sdk iphoneos -configuration Release -derivedDataPath build/ -archivePath ArchiveFolder/DemoCI.xcarchive PROVISIONING_PROFILE="TravisDestProfile.mobileprovision" ONLY_ACTIVE_ARCH=NO archive
 
 
after_script:
  - bash delete-keys.sh


after_success:
  - bash generateIPA.sh
  - bash ipa-upload.sh

env:
global:
  - bash set-environment.sh

xcode_project: DemoCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: DemoCITests
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone 8