os: osx
osx_image: xcode9.2 
language: swift
script: xcodebuild
xcode_project: DemoCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: DemoCITests
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPad Pro (9.7-inch)